namespace OstQuiz.Api.Domain;

/// <summary>
/// A pre-generated trimmed audio clip for a particular guess step.
/// Generated by the admin uploader (ffmpeg) so the full audio is not
/// downloadable before the final step. When a clip for a step is missing,
/// the API falls back to the puzzle's full audio.
/// </summary>
public class PuzzleClip
{
    public int Id { get; set; }

    public int PuzzleId { get; set; }
    public Puzzle Puzzle { get; set; } = null!;

    /// <summary>Guess step this clip belongs to (0..5).</summary>
    public int Step { get; set; }

    /// <summary>Clip length in seconds; null means full audio.</summary>
    public int? DurationSeconds { get; set; }

    /// <summary>Object key of the clip in the audio bucket.</summary>
    public required string ObjectKey { get; set; }
}
